input:
  csv:
    paths: ["./flight.csv"]
    parse_header_row: true
    delimiter: ','
pipeline:
  processors: 
    - log: 
        level: INFO
        message: ${!json()} 
output:
  kafka_franz:
    seed_brokers: ["localhost:19092"] # No default (required)
    topic: "flight" # No default (required)